### PR TITLE
Added test.py to testor1 branch

### PR DESCRIPTION
**Pull request by Aniket2208**
Hi,
I have commited test.py.
Kindly review it and accept!

Regards,
Testor1

### CODE REVIEW

**Comment by Ani2208** [comment]
Hi Aniket,
Please add more codes.

**Comment by Aniket2208** [comment]
Hi Ani,
I have added the additional checks!
Kindly approve.

Regards,
Testor1

**Comment by Ani2208** [comment]
Hi Aniket,
good to go to merge with master branch

**Comment by Aniket2208** [comment]
Done!

**Pull request merged**
